"""The presentation port: how the core loop talks to the outside (terminal,
TUI, or a parent agent). Adapters: ConsoleIO, SubagentIO, and the TUI.

The loop never imports a concrete UI — it depends only on this contract, so a
new front end is a new adapter, not a loop change.
"""

from typing import Protocol, runtime_checkable


@runtime_checkable
class AgentIO(Protocol):
    # decode rate (tok/s) of the most recent completed turn, for the
    # compaction trigger; SubagentIO proxies the parent's value.
    last_decode_tps: float

    # -- streaming lifecycle --
    def stream_started(self) -> None: ...
    def delta(self, kind: str, text: str) -> None: ...
    def stream_finished(self, usage) -> None: ...

    # -- tool activity --
    def tool_call(self, name: str, args: dict) -> None: ...
    def tool_result(self, output: str, is_error: bool) -> None: ...
    def notice(self, text: str) -> None: ...

    # -- interaction --
    def confirm(self, command: str) -> str | None: ...
    def drain_steers(self) -> list[str]: ...
    def should_abort(self) -> bool: ...
    def should_pause(self) -> bool: ...
    def clear_abort(self) -> None: ...
